name: Deployment
on:
    push:
        branches:
            - main
jobs:
    echo-some-text:
        name: Echo some text
        runs-on: ubuntu-latest
        steps:
            - run: echo "hey there"
    cypress-run:
        name: Cypress Tests
        needs:
            - echo-some-text
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v4.1.1
              with:
                spec: cypress/e2e/**/*.cy.js
            - name: Upload screenshots from failed tests
              uses: actions/upload-artifact@v3
              with:
                name: cypress-screenshots
                path: cypress/screenshots/**/*
              if: failure()
            - name: Upload mochawesome report
              run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                ls
                aws s3 sync mochawesome-report s3://espie-newman-reports --region=ap-southeast-2
                aws s3 sync cypress/screenshots s3://espie-newman-reports --region=ap-southeast-2
              if: always()
              