name: Deployment
on:
    push:
        branches:
            - main
jobs:
    echo-some-text:
        name: Echo some text
        runs-on: ubuntu-latest
        steps:
            - run: echo "hey there"
    list-files:
        name: List files
        runs-on: ubuntu-latest
        steps:
            - run: |
                cd ..
                pwd
                ls -lrt
    cypress-run:
        name: Cypress Tests
        needs:
            - list-files
        continue-on-error: true
        runs-on: ubuntu-latest
        steps:
            - name: Cypress run
              uses: cypress-io/github-action@v4.1.1
              with:
                spec: cypress/e2e/**/*.cy.ts
                working-directory: ..